enum AttackEnum {
  BALL = "BALL",
  BOOM_SPRITESHEET = "BOOM_SPRITESHEET",
  SPECIAL = "BALL_SPECIAL",
  BORDER = "BORDER",
  SHAPE = "SHAPE",
  PLANE_SPRITESHEET = "PLANE_SPRITESHEET",
}

export default AttackEnum;
