enum GeneralEnum {
  PLAYER_SPRITE_SHEET = "PLAYER_SPRITE_SHEET",
  AIM = "AIM",
  BLOOD_BAR = "BLOOD_BAR",
  STAMINA_BAR = "STAMINA_BAR",
  FLAG_SPRITE_SHEET = "FLAG_SPRITE_SHEET",
}

export default GeneralEnum;
