enum GeneralEnum {
  PLAYER_SPRITE_SHEET = "PLAYER_SPRITE_SHEET",
  AIM = "AIM",
  AIM_BAR = "AIM_BAR",
  BLOOD_BAR = "BLOOD_BAR",
  STAMINA_BAR = "STAMINA_BAR",
  STAMINA_BAR_FILL = "STAMINA_BAR_FILL",
  FLAG_SPRITE_SHEET = "FLAG_SPRITE_SHEET",
}

export default GeneralEnum;
