enum HudEnums {
  PLAYER_SPRITE_SHEET = "PLAYER_SPRITE_SHEET",
  AIM = "AIM",
  BLOOD_BAR = "BLOOD_BAR",
  STAMINA_BAR = "STAMINA_BAR",
  FLAG_SPRITE_SHEET = "FLAG_SPRITE_SHEET",
  RIGHT_BAR = "RIGHT_BAR",
  LEFT_BAR = "LEFT_BAR",
}

export default HudEnums;
