enum HudEnums {
  PLAYER_SPRITE_SHEET = "PLAYER_SPRITE_SHEET",
  AIM = "AIM",
  BLOOD_BAR = "BLOOD_BAR",
  STAMINA_BAR = "STAMINA_BAR",
  FLAG_SPRITE_SHEET = "FLAG_SPRITE_SHEET",
  RIGHT_BAR = "RIGHT_BAR",
  LEFT_BAR = "LEFT_BAR",
  ANGLE_HOLDER = "ANGLE_HOLDER",
  ANGLE = "ANGLE",
  ANGLE_POINTER_HOLDER = "ANGLE_POINTER_HOLDER",
  ANGLE_POINTER = "ANGLE_POINTER",
  ANGLE_POINTER_TRACE = "ANGLE_POINTER_TRACE",
  FLY_BUTTON_SPRITESHEET = "FLY_BUTTON_SPRITESHEET",
  FLY_BUTTON_SPRITESHEET_HITAREA = "FLY_BUTTON_SPRITESHEET_HITAREA",
}

export default HudEnums;
