enum PlayerEventsEnum {
    FORCE_CHANGED = "FORCE_CHANGED",
    ADD_PROP = "ADD_PROP",
    DIR_CHANGED = "DIR_CHANGED",
    FLY_CHANGED = "FLY_CHANGED",
    DIE = "DIE", 
    ATTACKING_CHANGED = "ATTACKING_CHANGED",
    BEGIN_NEW_TURN = "BEGIN_NEW_TURN",
    DANDER_CHANGED = "DANDER_CHANGED",
    BLOOD_CHANGED = "BLOOD_CHANGED",
    GUN_ANGEL_CHANGED = "GUN_ANGLE_CHANGED",
    PLAYER_ANGEL_CHANGED = "PLAYER_ANGLE_CHANGED",
    RESET = "RESET"
}

export default PlayerEventsEnum